### ISSUE TITLE
EnumFlags derive macro fails compilation if  '_' is in enum value 

### ISSUE THREAD

**Issue by Abelard0** [NieDzejkob/enumflags2#16]
Enum in sample below isn't compiled because of underscore in integer literals.
 
```
#[derive(EnumFlags, Copy, Clone, Debug, PartialEq)]
#[repr(u16)]
enum TextStyleMod
{
   Italic     = 0b00000000_00000100,
   Bold     = 0b00000000_00001000
}
```

**Comment by NieDzejkob** [comment]
Cannot reproduce. I created a project with `cargo new`, added this to the dependencies:
```
[dependencies]
enumflags2 = "*"
enumflags2_derive = "*"
```
and put this in the `main.rs`:
```
use enumflags2_derive::EnumFlags;

#[derive(EnumFlags, Copy, Clone, Debug, PartialEq)]
#[repr(u16)]
enum TextStyleMod
{
   Italic     = 0b00000000_00000100,
   Bold     = 0b00000000_00001000
}

fn main() {
    println!("Hello, world!");
}
```
This compiled.

**Comment by Abelard0** [comment]
You are right. Sorry for confusion. I found that compilation problem  wasn't related with underscore and compilation failed if I had value with all '1'. e.g

```
 use enumflags2_derive::EnumFlags;

#[derive(EnumFlags, Copy, Clone, Debug, PartialEq)]
#[repr(u16)]
enum TextStyleMod
{
   Italic     = 0b00000000_00000100,
   Bold     = 0b11111111_11111111
}

fn main() {
    println!("Hello, world!");
}

```

> error: proc-macro derive panicked
>  --> src/main.rs:3:10
>   |
> 3 | #[derive(EnumFlags, Copy, Clone, Debug, PartialEq)]
>   |          ^^^^^^^^^
>   |
>   = help: message: The following flags are not unique: ["TextStyleMod::Italic = 0b100", "TextStyleMod::Bold = 0b1111111111111111"]
> 
> error: aborting due to previous error
>
