### ISSUE TITLE
Publish `enumflags2_derive` 0.5.2

### ISSUE THREAD

**Issue by azriel91** [NieDzejkob/enumflags2#17]
Hiya, may I request that `enumflags2_derive` be published?

Currently only version `0.5.0` is published on crates.io, and `0.5.2` has the `syn`, `quote`, and `proc-macro2` dependencies bumped to `1.0`.

Thank you!

---

**edit:** ah, perhaps it's better to wait for 0.6 in #8

**Comment by NieDzejkob** [comment]
I'm confused. Version `enumflags2_derive 0.5.2` has never existed, and no commit in this repository looks like one. Either way, I'll write some documentation for #14 and release 0.6 in a few days at most.

**Comment by azriel91** [comment]
Ah, I made a mistake between `enumflag2_derive`and `enumflag2`'s Cargo.toml history, shall wait for 0.6, thank you!
