### ISSUE TITLE
Use of internal API needed for blanket trait implementations

### ISSUE THREAD

**Issue by zeenix** [NieDzejkob/enumflags2#23]
For the serde Serializer/Deserializer of my crate, I need the types to not only implement the Serialize/Deserialize traits but also another very simple one but I still want to provide blanket implementation wherever possible. Since bitfields are common place for this format, I would like to provide this implementation:

```
impl<V> VariantValue for enumflags2::BitFlags<V>
where
     V: VariantValue ,
{
     fn signature() -> Signature<'static> { 
         V::signature()
     } 
}
```

but this won't work:

```
error[E0277]: the trait bound `V: enumflags2::_internal::RawBitFlags` is not satisfied
   --> zvariant/src/variant_value.rs:130:9
    |
130 | impl<V> VariantValue for enumflags2::BitFlags<V>
    |         ^^^^^^^^^^^^ the trait `enumflags2::_internal::RawBitFlags` is not implemented for `V`
131 | where
132 |     V: VariantValue,
    |                     - help: consider further restricting type parameter `V`: `, V: enumflags2::_internal::RawBitFlags`
    |
    = note: required by `enumflags2::BitFlags`
```

I can of course solve this by following the suggestion in the error but I feel uncomfortable using internal API that could break any time. Could you please consider making this public API?

**Comment by NieDzejkob** [comment]
Sorry for taking so long to respond. This is quite perplexing, as I would rather avoid exposing the exact structure of the trait in the public API - adding new things to the trait can make implementing new features easier (or even possible). I am considering marking the trait `unsafe` and documenting the non-existent stability guarantees in the Safety section. Do you think this can break someone's workflow?

**Comment by zeenix** [comment]
No worries about delays. However, I'm not sure how to answer your question and how it solves my problem at hand. You can decide which API is internal and which is external but I can't implement a trait for `BitFlags` without `RawBitFlags` currently.

Having said that, I think I'll be using `flagset` crate instead which isn't as nice as your API or and popular even but it only exposes stable public API to public.

**Comment by NieDzejkob** [comment]
Perhaps I wasn't clear enough - I was proposing exposing the trait such that you can name it, but not implement it manually (or at least, be discouraged from implementing it).

**Comment by NieDzejkob** [comment]
I have stumbled upon a particularly nice solution. You can now create blanket implementations on `master`. I aim to release this tomorrow unless a flaw is discovered.

**Comment by zeenix** [comment]
> I was proposing exposing the trait such that you can name it, but not implement it manually (or at least, be discouraged from implementing it).

Ah, yes that would solve my problem I guess. :)

> I have stumbled upon a particularly nice solution. You can now create blanket implementations on `master`. I aim to release this tomorrow unless a flaw is discovered.

Cool, I'll check it out and try to test it too.

**Comment by zeenix** [comment]
@NieDzejkob So I tested master against my crate and it seems to all work well: https://gitlab.freedesktop.org/zeenix/zbus/-/commits/bitflags . I'll merge once you've released.

**Comment by zeenix** [comment]
@NieDzejkob Thanks so much for quick actions! I'm now a happy user :) https://gitlab.freedesktop.org/zeenix/zbus/-/merge_requests/40
