### ISSUE TITLE
Include LICENSE files in enumflags2_derive

### ISSUE THREAD

**Issue by ignatenkobrain** [NieDzejkob/enumflags2#27]
There are many variants of MIT and also Apache-2.0 requires text of license to be present along with source.

Please add those files into the _derive sub-crate, either using symlink or copy files inside subfolder.

Thanks!

**Comment by NieDzejkob** [comment]
The licenses are already present in the `enumflags` crate. For a while,
I was considering switching to the repository layout where the primary
crate is at the root of the workspace, and this is a good excuse, so I
did just that.

I'm not sure what the merit of also putting the license in the _derive
sub-crate is. Could you expand on your reasoning?

**Comment by ignatenkobrain** [comment]
We are taking archives from crates.io when building packages. Since those are separate units and are not aware of workspaces and such. That means they are built, tested and published separately.

So it is required to have the license text to be there. In latest cargo, if you specify `license-file` it would include that file from any place of workspace, but you can't specify multiple files there.

Is it a problem to just add a 2 symlinks in that folder?

**Comment by NieDzejkob** [comment]
Ah, that makes sense. I have added the files to the derive crate. I
decided against using symlinks, since I feel like they are somewhat
likely to break something.
