### ISSUE TITLE
BitFlags::empty() is not usable in a const context

### ISSUE THREAD

**Issue by NieDzejkob** [NieDzejkob/enumflags2#30]
Currently, no consideration for `const fn` is being made. This needs to be fixed before 1.0, especially the implications for MSRV.

**Comment by NieDzejkob** [comment]
A full `const fn`-friendly API is blocked on rust-lang/rfcs#2632, as otherwise the operator-overloading traits cannot be used. A workaround would be to add normal functions like `.or` and `.and`. Such a temporary API wart would mean that the next release won't be 1.0 after all.

**Comment by joseluis** [comment]
Ok I understand. 

I would love if you could publish a new crates.io release though, even without this feature, since I'm blocked from updating my crate for depending on the github repo.

**Comment by NieDzejkob** [comment]
Sorry, life got in the way. I've published `0.7.0-preview1`.

**Comment by marmeladema** [comment]
Hello and thank for your crate!
I find myself needing a `const` version of `BitFlags::from_flag`.
Looking at the code, it should be possible to constify a big part of the current API.
I think it's fine to have some methods const while other are not, it's still an improvement of usability for end user (myself :D).
Would you be inclined to accept such a PR? I willing to do the work if needed.

**Comment by NieDzejkob** [comment]
Sure! Last time I looked into this, there were some issues with trait bounds in const functions, but a Rust magician over at users.rust-lang.org [showed me some workarounds](https://github.com/rust-lang/rust/issues/57563) you might want to be aware of ;)

**Comment by NieDzejkob** [comment]
`BitFlags::EMPTY` works.
