### ISSUE TITLE
Support iterating backwards through `BitFlags`

### ISSUE THREAD

**Issue by Arcovion** [NieDzejkob/enumflags2#35]
I wanted to iterate all flags in reverse, but I get this error:
```rust
Flags::all().iter().rev()
                    ^^^ the trait `std::iter::DoubleEndedIterator` is not implemented for `impl std::iter::Iterator`
```
Internal constants don't have an issue with it:
```rust
use enumflags2::_internal::RawBitFlags;
Flags::FLAG_LIST.iter().rev()
```

**Comment by NieDzejkob** [comment]
I'm somewhat confused as to why you need this. In principle, `BitFlags` is an unordered container – there is no difference between `make_bitflags!(Foo::{A | B})` and `make_bitflags!(Foo::{B | A})`, and their iterators will return the elements in the same order.

Moreover, the order in which the flags get returned isn't that well-defined. Apart from the current order of "as they are declared", there's also the option of using bit-twiddling instructions to return them "lowest bit first". I would rather avoid explicitly making this choice a part of the public API...

So, could you tell me a bit more about why you want this?

**Comment by Arcovion** [comment]
Oh you're right, I shouldn't have been relying on the enum order. If I were to change the order the enum was declared it would break my code.
So the fact it's not supported is a good thing! I just wanted syntax sugar to avoid writing `.collect()` at the time 😁
I'm serialising/unserialising a bitmask to another weird format (ternary) one bit at a time; it's not related to the actual use of `BitFlags` and should indeed really be done with bit-twiddling—it's outside the scope of this crate.

This retrieves the flags in bit order, it's just not as concise:
```rust
let mut flags = Flags::all().iter().collect::<Vec<_>>();
flags.sort_unstable_by_key(|&flag| Flags::from_flag(flag).bits());

dbg!(flags.iter().collect::<Vec<_>>());
dbg!(flags.iter().rev().collect::<Vec<_>>());
```
